// CREA UN NODO DE TIPO ELEMENTO SEGUN EL NOMBRE DE LA ETIQUETA HTML QUE LE INDIQUEMOS
var botonVerMas = document.createElement("button");

// CREA UN NODO DE TEXTO EXPLICITADO ENTRE COMILLAS. NO SE VISUALIZA HASTA ASIGNARLO A UN ELEMENTO EXISTENTE DEL DOM
var botonTexto = document.createTextNode("Ver más");

// ADHIERE DENTRO DEL DOM UN ELEMENTO HIJO A UN ELEMENTO PADRE. SI EL ELEMENTO PADRE YA EXISTIA EN EL DOCUMENTO, CAMBIA SU POSICION HACIA EL OTRO ELEMENTO PADRE INDICADO. SI NO EXISTE, LO CREAMOS CON EL METODO 1.
botonVerMas.appendChild(botonTexto);
document.body.appendChild(botonVerMas);
